from typing import Protocol


class EdgarClient(Protocol):
    def has_going_concern(self, ticker: str) -> bool: ...
    def has_restatement(self, ticker: str, years: int = 3) -> bool: ...
    def has_active_enforcement(self, ticker: str) -> bool: ...
    def get_earnings_call_transcripts(self, ticker: str, quarters: int = 4) -> list[str]: ...
