from typing import Any, Protocol


class FirestoreClient(Protocol):
    def get(self, collection: str, document_id: str) -> dict[str, Any] | None: ...
    def set(self, collection: str, document_id: str, data: dict[str, Any]) -> None: ...
    def delete(self, collection: str, document_id: str) -> None: ...
