"""The stump survey as data: real EU issuer names, each tagged with the issuer
it belongs to.

WHY THE NAMES ARE COPIED HERE. They were collected on 2026-09-04 from two files
under `cache/`: the 90-entry offline corpus `identity_name_corpus.json` (both
sides of every pair — the yfinance reference name AND the OpenFIGI line name)
and the resolved issuer names quoted in the notes of
`eu_sec_source_census_v2.json`, the census over all 416 dotted EU tickers.
`cache/` is gitignored, so a test that read those files would pass on the
machine that produced them and fail (or silently skip) everywhere else — the
ADR-4 hermeticity trap. The names are therefore a frozen copy: a fixed set, which
is also what makes the survey a regression test rather than a moving measurement.

WHAT "DIFFERENT ISSUER" MEANS HERE. The first element of each row is the yfinance
ticker the name was observed under, and it is the identity claim: two rows with
different tickers are two different companies and must never normalise to the
same thing. That is a claim about the world, not something derivable from the
strings, so it is stated rather than computed — and the one place where it is NOT
true is stated too, in `SAME_COMPANY_ALIASES` below.
"""

# The single measured exception, and the reason the survey needs an explicit
# notion of issuer at all: RNL.PA and RNO.PA are two Yahoo symbols for ONE
# company, Renault SA, so their names colliding on 'RENAULT' is correct
# behaviour and not a stump. Every entry here is an excuse for a collision, so
# the survey also asserts that each one is still needed — a dead alias would be
# a place to hide a real collision in.
SAME_COMPANY_ALIASES: dict[str, str] = {"RNL.PA": "RNO.PA"}


def issuer_of(ticker: str) -> str:
    """The company a survey ticker belongs to, aliases resolved."""
    return SAME_COMPANY_ALIASES.get(ticker, ticker)


# (ticker the name was observed under, name as the source spelled it)
NAMES: tuple[tuple[str, str], ...] = (
    ("ITX.MC", "Industria de Diseño Textil, S.A."),
    ("ITX.MC", "INDUSTRIA DE DISENO TEXTIL"),
    ("BAYN.DE", "Bayer Aktiengesellschaft"),
    ("BAYN.DE", "BAYER AG-REG"),
    ("TEL2-B.ST", "Tele2 AB (publ)"),
    ("TEL2-B.ST", "TELE2 AB-B SHS"),
    ("MEL.MC", "Meliá Hotels International, S.A."),
    ("MEL.MC", "MELIA HOTELS INTERNATIONAL"),
    ("SKF-B.ST", "AB SKF (publ)"),
    ("SKF-B.ST", "SKF AB-B SHARES"),
    ("BME.L", "B&M European Value Retail plc"),
    ("BME.L", "B&M EUROPEAN VALUE RETAIL PL"),
    ("GLE.PA", "Société Générale Société anonyme"),
    ("GLE.PA", "SOCIETE GENERALE SA"),
    ("ALFA.ST", "Alfa Laval AB (publ)"),
    ("ALFA.ST", "ALFA LAVAL AB"),
    ("LXS.DE", "LANXESS Aktiengesellschaft"),
    ("LXS.DE", "LANXESS AG"),
    ("G1A.DE", "GEA Group Aktiengesellschaft"),
    ("G1A.DE", "GEA GROUP AG"),
    ("BT-A.L", "BT Group plc"),
    ("BT-A.L", "BRITANNIA GROUP PLC"),
    ("ASSA-B.ST", "ASSA ABLOY AB (publ)"),
    ("ASSA-B.ST", "ASSA ABLOY AB-B"),
    ("GLB.IR", "Beacon Hill CBO III Ltd"),
    ("GLB.IR", "GLANBIA PLC"),
    ("ALC.SW", "Alcon Inc."),
    ("ALC.SW", "ALCON INC"),
    ("ACA.PA", "Crédit Agricole S.A."),
    ("ACA.PA", "CREDIT AGRICOLE SA"),
    ("GF.SW", "Georg Fischer AG"),
    ("GF.SW", "FISCHER (GEORG)-REG"),
    ("EDP.LS", "EDP, S.A."),
    ("EDP.LS", "EDP SA"),
    ("GALP.LS", "Galp Energia, SGPS, S.A."),
    ("GALP.LS", "GALP ENERGIA SGPS SA"),
    ("MRL.MC", "MERLIN Properties SOCIMI, S.A."),
    ("VITR.ST", "Vitrolife AB (publ)"),
    ("VITR.ST", "VITROLIFE AB"),
    ("ANA.MC", "Acciona, S.A."),
    ("ANA.MC", "ACCIONA SA"),
    ("PAH3.DE", "Porsche Automobil Holding SE"),
    ("FLOW.AS", "Flow Traders Ltd."),
    ("FLOW.AS", "FLOW TRADERS LTD"),
    ("RNL.PA", "Renault SA"),
    ("VPLAY-B.ST", "Viaplay Group AB (publ)"),
    ("VPLAY-B.ST", "VIAPLAY GROUP AB"),
    ("AFX.DE", "Carl Zeiss Meditec AG"),
    ("AFX.DE", "CARL ZEISS MEDITEC AG - BR"),
    ("OR.PA", "L'Oréal S.A."),
    ("OR.PA", "L'OREAL"),
    ("REP.MC", "Repsol, S.A."),
    ("REP.MC", "REPSOL SA"),
    (
        "MUV2.DE",
        "Münchener Rückversicherungs-Gesellschaft Aktiengesellschaft in München",
    ),
    ("MUV2.DE", "MUENCHENER RUECKVER AG-REG"),
    ("COLR.BR", "Colruyt Group N.V."),
    ("COLR.BR", "COLRUYT GROUP N.V"),
    ("ATCO-A.ST", "Atlas Copco AB (publ)"),
    ("ATCO-A.ST", "ATLAS COPCO AB-A SHS"),
    ("SWED-A.ST", "Swedbank AB (publ)"),
    ("SWED-A.ST", "SWEDBANK AB - A SHARES"),
    ("LSG.OL", "Lerøy Seafood Group ASA"),
    ("LSG.OL", "LEROY SEAFOOD GROUP ASA"),
    ("ACX.MC", "Acerinox, S.A."),
    ("ACX.MC", "ACERINOX SA"),
    ("KNIN.SW", "Kuehne + Nagel International AG"),
    ("KNIN.SW", "KUEHNE + NAGEL INTL AG-REG"),
    ("AENA.MC", "Aena S.M.E., S.A."),
    ("AENA.MC", "AENA SME SA"),
    ("VPK.AS", "Koninklijke Vopak N.V."),
    ("VPK.AS", "VOPAK"),
    ("III.L", "3i Group Ord"),
    ("III.L", "3I GROUP PLC"),
    ("EVD.DE", "CTS Eventim AG & Co. KGaA"),
    ("EVD.DE", "CTS EVENTIM AG & CO KGAA"),
    ("ANE.MC", "Corporación Acciona Energías Renovables, S.A."),
    ("ANE.MC", "CORP ACCIONA ENERGIAS RENOVA"),
    ("OMV.VI", "OMV Aktiengesellschaft"),
    ("OMV.VI", "OMV AG"),
    ("SAND.ST", "Sandvik AB (publ)"),
    ("SAND.ST", "SANDVIK AB"),
    ("BEI.DE", "Beiersdorf Aktiengesellschaft"),
    ("BEI.DE", "BEIERSDORF AG"),
    ("IBE.MC", "Iberdrola, S.A."),
    ("IBE.MC", "IBERDROLA SA"),
    ("BKT.MC", "Bankinter, S.A."),
    ("BKT.MC", "BANKINTER SA"),
    ("SECU-B.ST", "Securitas AB (publ)"),
    ("SECU-B.ST", "SECURITAS AB-B SHS"),
    ("JMT.LS", "Jerónimo Martins, SGPS, S.A."),
    ("JMT.LS", "JERONIMO MARTINS"),
    ("AML.L", "Aston Martin Lagonda Global Holdings plc"),
    ("AML.L", "ASTON MARTIN LAGONDA GLOBAL"),
    ("CABK.MC", "CaixaBank, S.A."),
    ("CABK.MC", "CAIXABANK SA"),
    ("SGE.L", "The Sage Group plc"),
    ("SGE.L", "SAGE GROUP PLC/THE"),
    ("JD.L", "JD Sports Fashion Plc"),
    ("VOLV-B.ST", "AB Volvo (publ)"),
    ("VOLV-B.ST", "VOLVO AB-B SHS"),
    ("RMS.PA", "Hermès International Société en commandite par actions"),
    ("RMS.PA", "HERMES INTERNATIONAL"),
    ("AI.PA", "L'Air Liquide S.A."),
    ("AI.PA", "AIR LIQUIDE SA"),
    ("AF.PA", "Air France-KLM SA"),
    ("AF.PA", "AIR FRANCE-KLM"),
    ("BOL.ST", "Boliden AB (publ)"),
    ("BOL.ST", "BOLIDEN AB"),
    ("FLTR.L", "Flutter Entertainment PLC"),
    ("STERV.HE", "Stora Enso Oyj"),
    ("STERV.HE", "STORA ENSO OYJ-R SHS"),
    ("DIA.MC", "Distribuidora Internacional de Alimentación, S.A."),
    ("DIA.MC", "DISTRIBUIDORA INTERNACIONAL"),
    ("DLN.L", "Derwent London Plc"),
    ("ORSTED.CO", "Ørsted A/S"),
    ("ORSTED.CO", "ORSTED A/S"),
    ("SRT3.DE", "Sartorius Aktiengesellschaft"),
    ("SBRY.L", "J Sainsbury plc"),
    ("SBRY.L", "SAINSBURY (J) PLC"),
    ("BBVA.MC", "Banco Bilbao Vizcaya Argentaria, S.A."),
    ("BBVA.MC", "BANCO BILBAO VIZCAYA ARGENTA"),
    ("STJ.L", "St. James's Place plc"),
    ("STJ.L", "ST JAMES'S PLACE PLC"),
    ("BYG.L", "Big Yellow Group Plc"),
    ("IHG.L", "InterContinental Hotels Group PLC"),
    ("IHG.L", "INTERCONTINENTAL HOTELS GROU"),
    ("P911.DE", "Dr. Ing. h.c. F. Porsche AG"),
    ("SAN.MC", "Banco Santander, S.A."),
    ("SAN.MC", "BANCO SANTANDER SA"),
    ("IAG.L", "International Consolidated Airlines Group S.A."),
    ("IAG.L", "INTL CONSOLIDATED AIRLINE-DI"),
    ("CAST.ST", "Castellum AB (publ)"),
    ("CAST.ST", "CASTELLUM AB"),
    ("HUSQ-B.ST", "Husqvarna AB (publ)"),
    ("HUSQ-B.ST", "HUSQVARNA AB-B SHS"),
    ("BATS.L", "British American Tobacco p.l.c."),
    ("BATS.L", "BRITISH AMERICAN TOBACCO PLC"),
    ("HM-B.ST", "H & M Hennes & Mauritz AB (publ)"),
    ("HM-B.ST", "HENNES & MAURITZ AB-B SHS"),
    ("GFC.PA", "Gecina"),
    ("HNR1.DE", "Hannover Rück SE"),
    ("HNR1.DE", "HANNOVER RUECK SE"),
    ("SHB-B.ST", "Svenska Handelsbanken AB (publ)"),
    ("SHB-B.ST", "SVENSKA HANDELSBANKEN-B SHS"),
    ("ERIC-B.ST", "Telefonaktiebolaget LM Ericsson (publ)"),
    ("ERIC-B.ST", "ERICSSON LM-B SHS"),
    ("SEB-A.ST", "Skandinaviska Enskilda Banken AB (publ)"),
    ("SEB-A.ST", "SKANDINAVISKA ENSKILDA BAN-A"),
    ("SU.PA", "Schneider Electric S.E."),
    ("SU.PA", "SCHNEIDER ELECTRIC SE"),
    ("ACS.MC", "ACS, Actividades de Construcción y Servicios, S.A."),
    ("ACS.MC", "ACS ACTIVIDADES CONS Y SERV"),
    ("SAMPO.HE", "Sampo Oyj"),
    ("SAMPO.HE", "SAMPO OYJ-A SHS"),
    ("WISE.L", "Wise Group plc"),
    ("WISE.L", "WISE GROUP PLC-CL A"),
    ("RCO.PA", "Rémy Cointreau SA"),
    ("RCO.PA", "REMY COINTREAU"),
    ("UTG.L", "Unite Group PLC"),
    ("TEF.MC", "Telefónica, S.A."),
    ("TEF.MC", "TELEFONICA SA"),
    ("SIE.DE", "Siemens Aktiengesellschaft"),
    ("SIE.DE", "SIEMENS AG-REG"),
    ("OERL.SW", "OC Oerlikon Corporation AG"),
    ("OERL.SW", "OC OERLIKON CORP AG-REG"),
    ("CFR.SW", "Compagnie Financière Richemont SA"),
    ("CFR.SW", "CIE FINANCIERE RICHEMO-A REG"),
    ("NESN.SW", "Nestlé S.A."),
    ("NESN.SW", "NESTLE SA-REG"),
    ("1COV.DE", "COVESTRO AG"),
    ("8TRA.DE", "TRATON SE"),
    ("AAL.L", "ANGLO AMERICAN PLC"),
    ("ABF.L", "ASSOCIATED BRITISH FOODS PLC"),
    ("AC.PA", "ACCOR SA"),
    ("ADEN.SW", "ADECCO GROUP AG-REG"),
    ("ADM.L", "ADMIRAL GROUP PLC"),
    ("ADS.DE", "ADIDAS AG"),
    ("ADYEN.AS", "ADYEN NV"),
    ("AIR.PA", "AIRBUS SE"),
    ("AIXA.DE", "AIXTRON SE"),
    ("AKE.PA", "ARKEMA"),
    ("AKRBP.OL", "AKER BP ASA"),
    ("ALLFG.AS", "ALLFUNDS GROUP PLC"),
    ("ALV.DE", "ALLIANZ SE-REG"),
    ("AMBU-B.CO", "AMBU A/S-B"),
    ("ANTO.L", "ANTOFAGASTA PLC"),
    ("ARGX.BR", "ARGENX SE"),
    ("ASM.AS", "ASM INTERNATIONAL NV"),
    ("AT1.DE", "AROUNDTOWN SA"),
    ("ATO.PA", "ATOS GROUP"),
    ("AUTO.L", "AUTOTRADER GROUP PLC"),
    ("AZE.BR", "AZELIS GROUP NV"),
    ("BARN.SW", "BARRY CALLEBAUT AG-REG"),
    ("BAS.DE", "BASF SE"),
    ("BBY.L", "BALFOUR BEATTY PLC"),
    ("BC.MI", "BRUNELLO CUCINELLI SPA"),
    ("BEZ.L", "BEAZLEY PLC"),
    ("BN.PA", "DANONE"),
    ("BNP.PA", "BNP PARIBAS"),
    ("BNR.DE", "BRENNTAG SE"),
    ("BOSS.DE", "HUGO BOSS AG  -ORD"),
    ("BRBY.L", "BURBERRY GROUP PLC"),
    ("BTRW.L", "BARRATT REDROW PLC"),
    ("BVI.PA", "BUREAU VERITAS SA"),
    ("CA.PA", "CARREFOUR SA"),
    ("CAP.PA", "CAPGEMINI SE"),
    ("CBK.DE", "COMMERZBANK AG"),
    ("CCH.L", "COCA-COLA HBC AG-DI"),
    ("CDR.WA", "CD PROJEKT RED SA"),
    ("CLN.SW", "CLARIANT AG-REG"),
    ("CNA.L", "CENTRICA PLC"),
    ("CPG.L", "COMPASS GROUP PLC"),
    ("CPR.MI", "DAVIDE CAMPARI-MILANO NV"),
    ("CRDA.L", "CRODA INTERNATIONAL PLC"),
    ("CS.PA", "AXA SA"),
    ("CTEC.L", "CONVATEC GROUP PLC"),
    ("CTG.L", "CHRISTIE GROUP PLC"),
    ("DEMANT.CO", "DEMANT A/S"),
    ("DG.PA", "VINCI SA"),
    ("DHER.DE", "DELIVERY HERO SE"),
    ("DHL.DE", "DHL AG"),
    ("DIE.BR", "D'IETEREN GROUP"),
    ("DOCM.SW", "DOCMORRIS AG"),
    ("DPLM.L", "DIPLOMA PLC"),
    ("DSFIR.AS", "DSM-FIRMENICH AG"),
    ("DTG.DE", "DAIMLER TRUCK HOLDING AG"),
    ("EBS.VI", "ERSTE GROUP BANK AG"),
    ("EDEN.PA", "EDENRED"),
    ("EDV.L", "ENDEAVOUR MINING PLC"),
    ("EFGN.SW", "EFG INTERNATIONAL AG"),
    ("ELISA.HE", "ELISA OYJ"),
    ("EMSN.SW", "EMS-CHEMIE HOLDING AG-REG"),
    ("EN.PA", "BOUYGUES SA"),
    ("ENEL.MI", "ENEL SPA"),
    ("ENGI.PA", "ENGIE"),
    ("ENT.L", "ENTAIN PLC"),
    ("ENX.PA", "EURONEXT NV"),
    ("EVK.DE", "EVONIK INDUSTRIES AG"),
    ("EXO.AS", "EXOR NV"),
    ("EXPN.L", "EXPERIAN PLC"),
    ("EZJ.L", "EASYJET PLC"),
    ("FNTN.DE", "FREENET AG"),
    ("FORTUM.HE", "FORTUM OYJ"),
    ("FR.PA", "VALEO"),
    ("FRVIA.PA", "FORVIA"),
    ("G24.DE", "SCOUT24 SE"),
    ("GALE.SW", "GALENICA AG"),
    ("GAW.L", "GAMES WORKSHOP GROUP PLC"),
    ("GEBN.SW", "GEBERIT AG-REG"),
    ("GET.PA", "GETLINK SE"),
    ("GIVN.SW", "GIVAUDAN-REG"),
    ("GLEN.L", "GLENCORE PLC"),
    ("GN.CO", "GN STORE NORD A/S"),
    ("GRG.L", "GREGGS PLC"),
    ("HAS.L", "HAYS PLC"),
    ("HEI.DE", "HEIDELBERG MATERIALS AG"),
    ("HIK.L", "HIKMA PHARMACEUTICALS PLC"),
    ("HLMA.L", "HALMA PLC"),
    ("HOLN.SW", "HOLCIM LTD"),
    ("HSX.L", "HISCOX LTD"),
    ("HWDN.L", "HOWDEN JOINERY GROUP PLC"),
    ("ICG.L", "ICG PLC"),
    ("IGG.L", "IG GROUP HOLDINGS PLC"),
    ("IMB.L", "IMPERIAL BRANDS PLC"),
    ("IMI.L", "IMI PLC"),
    ("INCH.L", "INCHCAPE PLC"),
    ("INF.L", "INFORMA PLC"),
    ("INPST.AS", "INPOST SA"),
    ("INVP.L", "INVESTEC PLC"),
    ("IPN.PA", "IPSEN"),
    ("ISP.MI", "INTESA SANPAOLO"),
    ("ITRK.L", "INTERTEK GROUP PLC"),
    ("ITV.L", "ITV PLC"),
    ("JMAT.L", "JOHNSON MATTHEY PLC"),
    ("KBC.BR", "KBC GROUP NV"),
    ("KER.PA", "KERING"),
    ("KGF.L", "KINGFISHER PLC"),
    ("KNEBV.HE", "KONE OYJ-B"),
    ("KPN.AS", "KONINKLIJKE KPN NV"),
    ("LDO.MI", "LEONARDO SPA"),
    ("LEG.DE", "LEG IMMOBILIEN SE"),
    ("LGEN.L", "LEGAL & GENERAL GROUP PLC"),
    ("LHA.DE", "DEUTSCHE LUFTHANSA-REG"),
    ("LIGHT.AS", "SIGNIFY NV"),
    ("LONN.SW", "LONZA GROUP AG-REG"),
    ("LPP.WA", "LPP SA"),
    ("LSEG.L", "LONDON STOCK EXCHANGE GROUP"),
    ("MCG.L", "MOBICO GROUP PLC"),
    ("MELE.BR", "MELEXIS NV"),
    ("MF.PA", "WENDEL"),
    ("MNDI.L", "MONDI PLC"),
    ("MNG.L", "M&G PLC"),
    ("MONC.MI", "MONCLER SPA"),
    ("MONY.L", "MONY GROUP PLC"),
    ("MTX.DE", "MTU AERO ENGINES AG"),
    ("NEM.DE", "NEMETSCHEK SE"),
    ("NEX.PA", "NEXANS SA"),
    ("NEXI.MI", "NEXI SPA"),
    ("NHY.OL", "NORSK HYDRO ASA"),
    ("NN.AS", "NN GROUP NV"),
    ("NXT.L", "NEXT PLC"),
    ("OCDO.L", "OCADO GROUP PLC"),
    ("OCI.AS", "OCI NV"),
    ("ONTEX.BR", "ONTEX GROUP NV"),
    ("ORK.OL", "ORKLA ASA"),
    ("PBB.DE", "DEUTSCHE PFANDBRIEFBANK AG"),
    ("PGHN.SW", "PARTNERS GROUP HOLDING AG"),
    ("PNDORA.CO", "PANDORA A/S"),
    ("PNL.AS", "POSTNL NV"),
    ("PNN.L", "PENNON GROUP PLC"),
    ("PROX.BR", "PROXIMUS"),
    ("PRY.MI", "PRYSMIAN SPA"),
    ("PSN.L", "PERSIMMON PLC"),
    ("PST.MI", "POSTE ITALIANE SPA"),
    ("PUM.DE", "PUMA SE"),
    ("QLT.L", "QUILTER PLC"),
    ("RHM.DE", "RHEINMETALL AG"),
    ("RI.PA", "PERNOD RICARD SA"),
    ("RKT.L", "RECKITT BENCKISER GROUP PLC"),
    ("RMV.L", "RIGHTMOVE PLC"),
    ("RNO.PA", "RENAULT SA"),
    ("ROP.SW", "ROCHE HOLDING AG"),
    ("RXL.PA", "REXEL SA"),
    ("SAF.PA", "SAFRAN SA"),
    ("SALM.OL", "SALMAR ASA"),
    ("SCR.PA", "SCOR SE"),
    ("SCT.L", "SOFTCAT PLC"),
    ("SDR.L", "SCHRODERS PLC"),
    ("SDZ.SW", "SANDOZ GROUP AG"),
    ("SFOR.L", "S4 CAPITAL PLC"),
    ("SGSN.SW", "SGS SA-REG"),
    ("SIGN.SW", "SIG GROUP AG"),
    ("SIKA.SW", "SIKA AG-REG"),
    ("SIX2.DE", "SIXT SE"),
    ("SLHN.SW", "SWISS LIFE HOLDING AG-REG"),
    ("SMIN.L", "SMITHS GROUP PLC"),
    ("SOLB.BR", "SOLVAY SA"),
    ("SOON.SW", "SONOVA HOLDING AG-REG"),
    ("SPSN.SW", "SWISS PRIME SITE-REG"),
    ("SPX.L", "SPIRAX GROUP PLC"),
    ("SREN.SW", "SWISS RE AG"),
    ("SRG.MI", "SNAM SPA"),
    ("SSE.L", "SSE PLC"),
    ("STAN.L", "STANDARD CHARTERED PLC"),
    ("STMN.SW", "STRAUMANN HOLDING AG-REG"),
    ("SVT.L", "SEVERN TRENT PLC"),
    ("SW.PA", "SODEXO SA"),
    ("SY1.DE", "SYMRISE AG"),
    ("TATE.L", "TATE & LYLE PLC"),
    ("TEP.PA", "TELEPERFORMANCE"),
    ("TGS.OL", "TGS ASA"),
    ("TIT.MI", "TELECOM ITALIA SPA"),
    ("TKA.DE", "THYSSENKRUPP AG"),
    ("TLX.DE", "TALANX AG"),
    ("TMV.DE", "TEAMVIEWER SE"),
    ("TOM.OL", "TOMRA SYSTEMS ASA"),
    ("TOM2.AS", "TOMTOM NV"),
    ("TPK.L", "TRAVIS PERKINS PLC"),
    ("TRYG.CO", "TRYG A/S"),
    ("TSCO.L", "TESCO PLC"),
    ("TUI1.DE", "TUI AG"),
    ("UBI.PA", "UBISOFT ENTERTAINMENT"),
    ("UCG.MI", "UNICREDIT SPA"),
    ("UMG.AS", "UNIVERSAL MUSIC GROUP NV"),
    ("UMI.BR", "UMICORE"),
    ("UPM.HE", "UPM-KYMMENE OYJ"),
    ("VACN.SW", "VAT GROUP AG"),
    ("VALMT.HE", "VALMET OYJ"),
    ("VCT.PA", "VICAT"),
    ("VER.VI", "VERBUND AG"),
    ("VIE.PA", "VEOLIA ENVIRONNEMENT"),
    ("VIG.VI", "VIENNA INSURANCE GROUP AG"),
    ("VIV.PA", "VIVENDI SE"),
    ("VK.PA", "VALLOUREC SA"),
    ("VNA.DE", "VONOVIA SE"),
    ("VOE.VI", "VOESTALPINE AG"),
    ("VWS.CO", "VESTAS WIND SYSTEMS A/S"),
    ("WEIR.L", "WEIR PLC"),
    ("WIE.VI", "WIENERBERGER AG"),
    ("WKL.AS", "WOLTERS KLUWER"),
    ("WLN.PA", "WORLDLINE SA"),
    ("WTB.L", "WHITBREAD PLC"),
    ("YAR.OL", "YARA INTERNATIONAL ASA"),
    ("ZAL.DE", "ZALANDO SE"),
    ("ZURN.SW", "ZURICH INSURANCE GROUP AG"),
)
